CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ApiLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActionName" text,
    "EventType" text NOT NULL,
    "ResponseStatusCode" integer NOT NULL,
    "Url" text NOT NULL,
    "UserIp" text,
    "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "DurationMsec" integer NOT NULL,
    "LogDetail" jsonb NOT NULL,
    "ModifiedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "Status" boolean NOT NULL,
    "TraceId" text NOT NULL,
    "UserId" text,
    CONSTRAINT "PK_ApiLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "AuditLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AuditScopeId" uuid NOT NULL,
    "Action" text NOT NULL,
    "ChangedValues" jsonb,
    "Error" text,
    "PrimaryKey" text NOT NULL,
    "Table" text NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "DurationMsec" integer NOT NULL,
    "LogDetail" jsonb NOT NULL,
    "ModifiedOn" timestamp with time zone NOT NULL,
    "Status" boolean NOT NULL,
    "TraceId" text NOT NULL,
    "UserId" text,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "ScheduledJobs" (
    "ScheduledJobId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ApiMethod" character varying(20) NOT NULL,
    "ApiType" character varying(20) NOT NULL,
    "ApiUrl" text NOT NULL,
    "CronExpression" text NOT NULL,
    "JobName" text NOT NULL,
    "ApiHeaders" jsonb,
    "ApiIdempotencyKey" text,
    "ApiJsonBody" jsonb,
    "Oauth2BaseUri" text,
    "Oauth2ClientId" text,
    "Oauth2ClientScopes" jsonb,
    "Oauth2ClientSecret" text,
    "ClientId" text NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreateRequestId" text NOT NULL,
    "CreatorId" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ModifiedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "ModifierId" text NOT NULL,
    CONSTRAINT "PK_ScheduledJobs" PRIMARY KEY ("ScheduledJobId")
);

CREATE INDEX "IX_ApiLogs_ActionName" ON "ApiLogs" ("ActionName");

CREATE INDEX "IX_ApiLogs_CreatedOn" ON "ApiLogs" ("CreatedOn");

CREATE INDEX "IX_ApiLogs_EventType" ON "ApiLogs" ("EventType");

CREATE INDEX "IX_ApiLogs_ModifiedOn" ON "ApiLogs" ("ModifiedOn");

CREATE INDEX "IX_ApiLogs_ResponseStatusCode" ON "ApiLogs" ("ResponseStatusCode");

CREATE INDEX "IX_ApiLogs_TraceId" ON "ApiLogs" ("TraceId");

CREATE INDEX "IX_ApiLogs_Url" ON "ApiLogs" ("Url");

CREATE INDEX "IX_ApiLogs_UserId" ON "ApiLogs" ("UserId");

CREATE INDEX "IX_ApiLogs_UserIp" ON "ApiLogs" ("UserIp");

CREATE INDEX "IX_ScheduledJobs_ClientId" ON "ScheduledJobs" ("ClientId");

CREATE INDEX "IX_ScheduledJobs_CreatedOn" ON "ScheduledJobs" ("CreatedOn");

CREATE UNIQUE INDEX "IX_ScheduledJobs_CreateRequestId_ClientId" ON "ScheduledJobs" ("CreateRequestId", "ClientId");

CREATE INDEX "IX_ScheduledJobs_CreatorId" ON "ScheduledJobs" ("CreatorId");

CREATE UNIQUE INDEX "IX_ScheduledJobs_JobName" ON "ScheduledJobs" ("JobName") WHERE "IsDeleted" = false;

CREATE INDEX "IX_ScheduledJobs_ModifiedOn" ON "ScheduledJobs" ("ModifiedOn");

CREATE INDEX "IX_ScheduledJobs_ModifierId" ON "ScheduledJobs" ("ModifierId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241211043234_InitialCreate', '8.0.11');

COMMIT;

